### ISSUE TITLE
`trigger_error` in CurlHttpClient

### ISSUE THREAD

**Issue by shabbyrobe** [mekras/psr7-client#7]
This is a tricky one. In all of my projects, every single error, warning, notice, or otherwise is turned into an Exception. Projects don't really use the PHP error API any more, and PHP itself is moving away from it to Exceptions [wherever they possibly can](https://wiki.php.net/rfc/engine_exceptions).

I actually had to change my entire project to support the bump to 3.04 because of the `trigger_error` call in `CurlHttpClient->send()`, which is a bit more than I'd usually expect from a point release. Sorry, I know this does seem a bit silly considering just yesterday a point release was exactly what I was recommending!

But I do think the `trigger_error` perhaps might be overkill when the `@deprecated` attribute is already applied and it exposes people who treat all PHP errors as fatal to an effective breaking API change. If the project is semantically versioned, breaking API changes warrant major versions, but a new major version definitely seems like overkill for the sake of a `trigger_error`!

What do you think?

**Comment by mekras** [comment]
First of all, this project will be closed in the near future. The codebase is transferred to https://github.com/php-http/curl-client (currently in alpha). psr7-client will be changed to be compatible with curl-client (to ease migration), then frozen and removed after some time.

`trigger_error` is used in `send` because this situation is not an exception. Program flow should not be interrupted here. Moreover, referenced RFC is just about fatal errors (which breaks flow).

In my opinion notices, warnings or other non fatals should not be converted to Exception in production, only in develop environment. But it's just my opinion.

Any way. Method `send` is deprecated and will be removed in [4.00](https://github.com/mekras/psr7-client/milestones/4.00).

**Comment by shabbyrobe** [comment]
I was actually just suggesting the `trigger_error` be removed completely, but no matter, if you'd prefer it stays that's entirely your call :)
